"""empty message

Revision ID: 3ba715c96ee2
Revises: df3a775a9518
Create Date: 2022-02-08 00:03:24.100655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba715c96ee2'
down_revision = 'df3a775a9518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
