"""empty message

Revision ID: 81c777f3b94e
Revises: 92a14bf8072d
Create Date: 2022-02-18 03:59:07.367934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c777f3b94e'
down_revision = '92a14bf8072d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.String(length=20), nullable=True))
        batch_op.drop_column('fhoto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fhoto_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('photo_id')

    # ### end Alembic commands ###
