"""empty message

Revision ID: c45157a5e29f
Revises: 75fdecd20906
Create Date: 2022-01-31 06:55:14.085242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45157a5e29f'
down_revision = '75fdecd20906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
    "fk":"fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('reserves', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_reserves_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reserves_conference_id_conferences', type_='foreignkey')
        batch_op.create_foreign_key('fk_reserves_conference_id_conferences', 'conferences', ['conference_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_reserves_user_id_users', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    naming_convention = {
    "fk":"fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserves', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_reserves_conference_id_conferences', type_='foreignkey')
        batch_op.drop_constraint('fk_reserves_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_reserves_conference_id_conferences', 'conferences', ['conference_id'], ['id'])
        batch_op.create_foreign_key('fk_reserves_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
